services:
  branch_b:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sdwan_branch_b
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      FIBER_IP: 172.31.10.2
      SAT_IP: 172.31.20.2
      BRANCH_NAME: branch_b
      PEER_FIBER_IP: 172.31.10.1
      PEER_SAT_IP: 172.31.20.1
      PEER_BRANCH_NET: 172.31.100.0/24
    networks:
      fiber_net:
        ipv4_address: 172.31.10.2
      sat_net:
        ipv4_address: 172.31.20.2
      branch_b_lan:
        ipv4_address: 172.31.200.2

  branch_a:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sdwan_branch_a
    privileged: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - branch_b
    environment:
      BRANCH_NAME: branch_a
      FIBER_IP: 172.31.10.3
      SAT_IP: 172.31.20.3 
      PEER_FIBER_IP: 172.31.10.2
      PEER_SAT_IP: 172.31.20.2
      PEER_BRANCH_NET: 172.31.200.0/24
    networks:
      fiber_net:
        ipv4_address: 172.31.10.1
      sat_net:
        ipv4_address: 172.31.20.1
      branch_a_lan:
        ipv4_address: 172.31.100.2

networks:
  fiber_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.10.0/29
          gateway: 172.31.10.5
  sat_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.20.0/29
          gateway: 172.31.20.5
  branch_a_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.100.0/29
          gateway: 172.31.100.5
  branch_b_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.200.0/29
          gateway: 172.31.200.5